data:
  dataset_type: 'aig-directed-multiclass'
  m: 16  # Adjust based on your graph analysis
  graph_file: 'dataset/small_inputs8_outputs8.pkl'  # Update with your actual file path
  use_bfs: true
  max_graphs: null  # Set a number for debugging with fewer graphs

model:
  mode: 'directed-multiclass'
  edge_model: 'mlp'  # Use 'mlp' or 'rnn'

  GraphRNN:
    embedding_size: 128
    hidden_size: 256
    num_layers: 3
    edge_feature_len: 3  # 3 edge types for AIGs

  EdgeMLP:
    hidden_size: 128
    edge_feature_len: 3

  EdgeRNN:
    embedding_size: 64
    hidden_size: 128
    num_layers: 3
    edge_feature_len: 3

train:
  batch_size: 32
  lr: 0.001
  steps: 20000
  print_iter: 100
  checkpoint_iter: 1000
  checkpoint_dir: 'checkpoints'
  log_dir: 'logs'
  lr_schedule_milestones: [3000, 6000, 9000]
  lr_schedule_gamma: 0.3