# Config: GRU Node + MLP Edge
data:
  dataset_type: 'aig-directed-multiclass'
  graph_file: 'dataset/final_data.pkl'
  use_bfs: false
  max_graphs: null

model:
  mode: 'directed-multiclass'
  use_lstm: false         # GRU Node
  use_attention: false    # No Node Attention
  edge_model: 'mlp'       # MLP Edge

  GraphRNN:
    embedding_size: 384
    hidden_size: 768      # Input size for EdgeMLP
    num_layers: 3
    edge_feature_len: 3
    output_size: null     # Not needed for EdgeMLP

  EdgeMLP:
    hidden_size: 768      # Internal hidden size for MLP
    edge_feature_len: 3
    # input_size automatically set from GraphRNN.hidden_size
    # output_size automatically set based on data

train:
  batch_size: 32
  lr: 0.001              # Initial Learning Rate
  steps: 60000            # Total training steps
  print_iter: 100
  checkpoint_iter: 6000
  checkpoint_dir: 'checkpoints/checkpoints_gru_mlp' # Specific directory
  log_file: 'train_results/logs_gru_mlp'               # Specific directory
  # lr_schedule_* removed; code uses CosineAnnealingLR