# Config: LSTM Node + standard RNN Edge
data:
  dataset_type: 'aig-directed-multiclass'
  graph_file: 'dataset/data.pkl'
  use_bfs: false
  max_graphs: null

model:
  mode: 'directed-multiclass'
  use_lstm: true          # LSTM Node
  use_attention: false    # No Node Attention
  edge_model: 'rnn'       # Use standard EdgeRNN (maps to EdgeLSTM because use_lstm=true)

  GraphLSTM:              # Used because use_lstm: true, use_attention: false
    embedding_size: 128
    hidden_size: 256
    num_layers: 4
    edge_feature_len: 3
    output_size: 128      # MUST match EdgeLSTM.hidden_size

  EdgeLSTM:               # Used because edge_model: 'rnn' and use_lstm: true
    embedding_size: 64
    hidden_size: 128      # MUST match GraphLSTM.output_size
    num_layers: 4
    edge_feature_len: 3

train:
  batch_size: 32
  lr: 0.0005              # Initial Learning Rate
  steps: 75000            # Total training steps
  print_iter: 100
  checkpoint_iter: 7500
  checkpoint_dir: 'checkpoints/checkpoints_lstm_rnn' # Specific directory
  log_file: 'train_results/logs_lstm_rnn'               # Specific directory
  # lr_schedule_* removed; code uses CosineAnnealingLR