# Config: GRU Node + RNN Edge
data:
  dataset_type: 'aig-directed-multiclass'
  graph_file: 'dataset/final_data.pkl'
  use_bfs: false
  max_graphs: null
  m: 88

model:
  mode: 'directed-multiclass'
  use_lstm: false         # GRU Node
  use_attention: false    # No Node Attention
  edge_model: 'rnn'       # RNN Edge

  GraphRNN:
    embedding_size: 384
    hidden_size: 768
    num_layers: 4
    edge_feature_len: 3
    output_size: 384      # MUST match EdgeRNN.hidden_size

  EdgeRNN:
    embedding_size: 192
    hidden_size: 384      # MUST match GraphRNN.output_size
    num_layers: 4
    edge_feature_len: 3

train:
  batch_size: 64
  lr: 0.001              # Initial Learning Rate
  steps: 75000            # Total training steps
  print_iter: 100
  checkpoint_iter: 7500
  checkpoint_dir: 'checkpoints/checkpoints_gru_rnn' # Specific directory
  log_file: 'train_results/logs_gru_rnn'               # Specific directory
  # lr_schedule_* removed; code uses CosineAnnealingLR