data:
  dataset_type: 'aig-directed-multiclass'
  graph_file: 'dataset/inputs8_outputs8max_nodes128max.pkl' # CHECK PATH
  use_bfs: false
  max_graphs: null

model:
  mode: 'directed-multiclass'
  use_lstm: true                  # <-- Use LSTM instead of GRU
  use_attention: false            # <-- No Attention for Node model
  edge_model: 'rnn'               # <-- Use 'rnn' for base EdgeLSTM (needs setup_models update)

  # --- LSTM Model Settings ---
  GraphLSTM:                      # Parameters for GraphLevelLSTM
    embedding_size: 256
    hidden_size: 512
    num_layers: 4
    edge_feature_len: 3
    output_size: 256              # Output projection size for EdgeLSTM input

  EdgeLSTM:                       # Parameters for EdgeLevelLSTM
    embedding_size: 128
    hidden_size: 256              # Should match GraphLSTM.output_size
    num_layers: 4
    edge_feature_len: 3

  # --- Unused/Ignored Sections (parameters might be different for GRU/Attention) ---
  # GraphRNN: ...
  # EdgeRNN: ...
  # GraphAttentionLSTM: ...
  # EdgeAttentionLSTM: ...
  # EdgeMLP: ...

train:
  batch_size: 32
  lr: 0.001
  steps: 50000
  print_iter: 100
  checkpoint_iter: 1000
  checkpoint_dir: 'lstm_checkpoints'    # Specific directory
  log_dir: 'lstm_logs'                  # Specific directory
  lr_schedule_milestones: [10000, 20000, 30000, 40000]
  lr_schedule_gamma: 0.3