data:
  dataset_type: 'aig-directed-multiclass'
  graph_file: 'dataset/inputs8_outputs8max_nodes128max.pkl'
  use_bfs: false
  max_graphs: null

model:
  mode: 'directed-multiclass'
  edge_model: 'rnn' # Use 'mlp'

  GraphRNN:
    use_attention: false    # <<< Flag set to false
    use_lstm: false
    embedding_size: 384
    hidden_size: 768       # Needed for EdgeMLP input_size
    num_layers: 4
    edge_feature_len: 3
    # attention_heads: 8      # Ignored if use_attention: false
    # attention_dropout: 0.1 # Ignored if use_attention: false
    output_size: 384      # Not needed when edge_model is 'mlp'

#  EdgeMLP: # Used settings
#    hidden_size: 512      # Internal hidden size for MLP
#    edge_feature_len: 3
#    # input_size is automatically set from GraphRNN.hidden_size in setup_models
#    # output_size is automatically set from effective_input_size in setup_models

  EdgeRNN: # Ignored settings
    embedding_size: 192
    hidden_size:  384
    num_layers: 4
    edge_feature_len: 3

train:
  batch_size: 32
  lr: 0.001
  steps: 75000
  print_iter: 100
  checkpoint_iter: 7500
  checkpoint_dir: 'checkpoints_GraphLevelRNN' # Specific directory
  log_dir: 'logs_GraphLevelRNNP'            # Specific directory
  lr_schedule_milestones: [5000, 10000, 15000, 20000, 30000, 40000, 45000]
  lr_schedule_gamma: 0.3