data:
  dataset_type: 'aig-directed-multiclass'
  m: 16  # Adjust based on your graph analysis
  graph_file: 'dataset/inputs8_outputs2.pkl'  # Update with your actual file path
  use_bfs: false
  max_graphs: null  # Set a number for debugging with fewer graphs

model:
  predict_node_types: false  # Set to false to disable node type prediction
  num_node_types: 4  # ZERO, PI, AND, PO
  mode: 'directed-multiclass'
  edge_model: 'mlp'  # Use 'mlp' or 'rnn'

  # Truth table conditioning settings
  truth_table_conditioning: true
  n_inputs: 8   # Number of inputs in your AIGs
  n_outputs: 2  # Number of outputs in your AIGs

  GraphRNN:
    embedding_size: 128
    hidden_size: 256
    num_layers: 3
    edge_feature_len: 3  # 3 edge types for AIGs

  EdgeMLP:
    hidden_size: 256
    edge_feature_len: 3

  EdgeRNN:
    embedding_size: 64
    hidden_size: 256
    num_layers: 3
    edge_feature_len: 3

train:
  batch_size: 32
  lr: 0.001
  steps: 15000
  print_iter: 100
  checkpoint_iter: 1000
  checkpoint_dir: 'runs/tt_checkpoints'
  log_dir: 'runs/tt_logs'
  lr_schedule_milestones: [3000, 6000, 9000]
  lr_schedule_gamma: 0.3