# Config file for LSTM node and edge models (No Attention) - CORRECTED
data:
  dataset_type: 'aig-directed-multiclass'
  graph_file: 'dataset/inputs8_outputs8max_nodes128max.pkl' # CHECK PATH
  use_bfs: false
  max_graphs: null

model:
  mode: 'directed-multiclass'
  use_lstm: true                  # Use LSTM
  use_attention: false            # No Attention
  edge_model: 'rnn'               # Use base EdgeLSTM (matched with 'rnn' in updated setup_models)

  GraphLSTM:                      # Parameters for GraphLevelLSTM
    embedding_size: 256
    hidden_size: 512
    num_layers: 4
    edge_feature_len: 3           # <-- Define explicitly here
    output_size: 256              # For EdgeLSTM input

  EdgeLSTM:                       # Parameters for EdgeLevelLSTM
    embedding_size: 128
    hidden_size: 256              # Matches GraphLSTM.output_size
    num_layers: 4
    edge_feature_len: 3           # <-- Define explicitly here

  # --- Unused/Ignored Sections ---
  # GraphRNN: ...
  # EdgeRNN: ...
  # GraphAttentionLSTM: ...
  # EdgeAttentionLSTM: ...
  # EdgeMLP: ...

train:
  batch_size: 32
  lr: 0.001
  steps: 50000
  print_iter: 100
  checkpoint_iter: 5000
  checkpoint_dir: 'lstm_checkpoints'
  log_dir: 'lstm_logs'
  lr_schedule_milestones: [10000, 20000, 30000, 40000]
  lr_schedule_gamma: 0.3