data:
  dataset_type: 'aig-directed-multiclass'
  #m: 16  # Adjust based on your graph analysis  <-- CAN BE REMOVED/IGNORED
  graph_file: 'dataset/inputs8_outputs8less.pkl'  # Update with your actual file path <-- CHECK PATH
  use_bfs: false  # <--- CORRECT for Topological Sort
  max_graphs: null

model:
  mode: 'directed-multiclass' # Correct for AIGs
  edge_model: 'mlp'  # Use 'mlp' or 'rnn' <-- CURRENT CHOICE (See discussion below)

  GraphRNN:
    embedding_size: 128
    hidden_size: 256
    num_layers: 3
    edge_feature_len: 3  # <-- CORRECT (None, Regular, Inverted)

  EdgeMLP: # Settings used if edge_model is 'mlp'
    hidden_size: 256
    edge_feature_len: 3 # <-- CORRECT

  EdgeRNN: # Settings used if edge_model is 'rnn'
    embedding_size: 64
    hidden_size: 256
    num_layers: 3
    edge_feature_len: 3 # <-- CORRECT

train:
  batch_size: 32
  lr: 0.001
  steps: 15000
  print_iter: 100
  checkpoint_iter: 1000
  checkpoint_dir: 'base_checkpoints'
  log_dir: 'base_logs'
  lr_schedule_milestones: [3000, 6000, 9000]
  lr_schedule_gamma: 0.3